# Continuous Integration
#
# References:
#
# - https://github.com/actions/checkout
# - https://github.com/actions/setup-node
# - https://docs.github.com/actions/guides/building-and-testing-nodejs

---
name: continuous-integration
on: [pull_request]
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN_ADMIN }}
      PAT_GPR: ${{ secrets.PAT_GPR_ADMIN }}
    strategy:
      matrix:
        node: [15, 16]
    steps:
      - id: checkout
        name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - id: setup-node
        name: Setup Node ${{ matrix.node }} environment
        uses: actions/setup-node@v2
        with:
          always-auth: true
          cache: yarn
          node-version: ${{ matrix.node }}
          registry-url: https://npm.pkg.github.com
          scope: '@${{ github.repository_owner }}'
      - id: install
        name: Install dependencies
        run: yarn --immutable
        env:
          NODE_AUTH_TOKEN: ${PAT_GPR}
      - id: check-format
        name: Check code formatting
        run: yarn check:format
      - id: check-code-style
        name: Check code style
        run: yarn check:style --max-warnings 0
      - id: check-build
        name: Check build
        run: yarn build
        env:
          NODE_OPTIONS: -r tsconfig-paths/register
